package com.neo.aiassistant.data.agent

/**
 * Represents the current state of the AI Agent's reasoning and execution loop.
 */
sealed interface AgentState {
    /** The agent is idle and waiting for user input. */
    object Idle : AgentState
    
    /** The agent is currently planning its next steps or reasoning about the user's request. */
    object Planning : AgentState
    
    /** 
     * The agent is currently executing a specific tool. 
     * @property toolName The name of the tool being executed.
     */
    data class ExecutingTool(val toolName: String) : AgentState
    
    /** 
     * The agent is waiting for user confirmation before proceeding with a tool execution.
     * @property toolName The name of the tool requiring confirmation.
     * @property message A message to show to the user explaining why confirmation is needed.
     */
    data class WaitingForConfirmation(val toolName: String, val message: String) : AgentState
    
    /** The agent has completed its task successfully. */
    object Completed : AgentState
    
    /** 
     * The agent encountered an error during its reasoning or execution loop.
     * @property message A description of the error.
     */
    data class Error(val message: String) : AgentState
}

/**
 * Represents a parsed tool call generated by the AI model.
 */
data class ToolCall(
    val toolName: String,
    val arguments: Map<String, String>
)

/**
 * Represents the result of an assistant turn.
 */
sealed class AssistantTurnResult {
    data class Text(val content: String) : AssistantTurnResult()
    data class ToolRequest(val toolCall: ToolCall) : AssistantTurnResult()
    data class Error(val message: String, val throwable: Throwable? = null) : AssistantTurnResult()
}

/**
 * Represents a single step in the agent's execution history.
 */
data class AgentStep(
    val toolCall: ToolCall,
    val result: ToolResult
)

/**
 * Metadata about a tool for registration and discovery.
 */
data class ToolDefinition(
    val name: String,
    val description: String,
    val inputSchema: String
)
