package com.neo.aiassistant.data.agent

/**
 * Represents the current state of the AI Agent's reasoning and execution loop.
 */
sealed interface AgentState {
    /** The agent is idle and waiting for user input. */
    object Idle : AgentState
    
    /** The agent is currently planning its next steps or reasoning about the user's request. */
    object Planning : AgentState
    
    /** 
     * The agent is currently executing a specific tool. 
     * @property toolName The name of the tool being executed.
     */
    data class ExecutingTool(val toolName: String) : AgentState
    
    /** 
     * The agent is waiting for user confirmation before proceeding with a tool execution.
     * @property toolName The name of the tool requiring confirmation.
     * @property message A message to show to the user explaining why confirmation is needed.
     */
    data class WaitingForConfirmation(val toolName: String, val message: String) : AgentState
    
    /** The agent has completed its task successfully. */
    object Completed : AgentState
    
    /** 
     * The agent encountered an error during its reasoning or execution loop.
     * @property message A description of the error.
     */
    data class Error(val message: String) : AgentState
}

/**
 * Represents a parsed tool call generated by the AI model.
 *
 * This data class captures the intent of the model to use a specific tool with
 * a set of arguments.
 *
 * @property toolName The unique identifier of the tool to be called.
 * @property arguments A map of argument names to their string values for the tool call.
 */
data class ToolCall(
    val toolName: String,
    val arguments: Map<String, String>
)

/**
 * Represents a single step in the agent's execution history.
 *
 * Each step consists of a tool call made by the model and the resulting output from that tool.
 *
 * @property toolCall The tool call that was executed.
 * @property result The outcome of the tool execution.
 */
data class AgentStep(
    val toolCall: ToolCall,
    val result: ToolResult
)
