package com.neo.chevere.domain

/**
 * Represents a single message in a chat conversation.
 *
 * @property text The content of the message.
 * @property isUser `true` if the message was sent by the user, `false` if it was generated by the AI.
 * @property inferenceTimeMs The time taken in milliseconds to generate the response (if applicable).
 * @property imageUri Optional URI of an image associated with the message.
 * @property modelName Optional name of the AI model that generated the message.
 */
data class ChatMessage(
    val text: String,
    val isUser: Boolean,
    val inferenceTimeMs: Long? = null,
    val imageUri: String? = null,
    val modelName: String? = null
)
