package com.neo.chevere.domain

import com.neo.chevere.data.agent.AgentState

/**
 * Represents a single message in a chat conversation.
 *
 * @property text The content of the message.
 * @property isUser `true` if the message was sent by the user, `false` if it was generated by the AI.
 * @property inferenceTimeMs The time taken in milliseconds to generate the response (if applicable).
 * @property inputTokenCount Approximate number of prompt tokens for the response, if known.
 * @property outputTokenCount Approximate number of generated response tokens, if known.
 * @property imageUri Optional URI of an image associated with the message.
 * @property modelName Optional name of the AI model that generated the message.
 * @property isExplicitImage `true` when the attached image should support explicit-content masking.
 * @property isImageMasked `true` when an explicit image attachment is currently hidden behind a mask.
 * @property agentState Optional AI Agent state/steps associated with this message.
 */
data class ChatMessage(
    val text: String,
    val isUser: Boolean,
    val inferenceTimeMs: Long? = null,
    val inputTokenCount: Int? = null,
    val outputTokenCount: Int? = null,
    val imageUri: String? = null,
    val modelName: String? = null,
    val isExplicitImage: Boolean = false,
    val isImageMasked: Boolean = false,
    val agentState: AgentState? = null
)
